getwd()
setwd("C:/Free time")
nodes<-read.csv("nodes.csv",header=T,as.is = T)
head(nodes)
links<-read.csv("edges1.csv",header=T,as.is = T)
head(links)
net <- graph.data.frame(d=links, vertices=nodes, directed=T)
m=as.matrix(net)
get.adjacency(m)
plot(net)
